export const FETCH_GAME_REQUEST = 'FETCH_GAMES_REQUEST';
export const FETCH_GAME_SUCCESS = 'FETCH_GAMES_SUCCESS';
export const FETCH_GAME_FAILURE = 'FETCH_GAMES_FAILURE';

export const CREATE_GAME_REQUEST = 'CREATE_GAME_REQUEST';
export const CREATE_GAME_SUCCESS = 'CREATE_GAME_SUCCESS';
export const CREATE_GAME_FAILURE = 'CREATE_GAME_FAILURE';

export const UPDATE_GAME_REQUEST = 'DELETE_GAME_REQUEST';
export const UPDATE_GAME_SUCCESS = 'DELETE_GAME_SUCCESS';
export const UPDATE_GAME_FAILURE = 'DELETE_GAME_FAILURE';