version: '3.9'

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1004:1004"
    networks:
      - consul-net

networks:
  consul-net:
    external: true